name: CI
on: [push]

env:
  platform: Linux # O 'aws' según el momento del video
  region: us-east-1 # Ejemplo basado en la explicación
  account: 12345 # Ejemplo basado en la explicación

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display message
        run: echo "Hola mundo"
      
      - name: Mostrando variables de entorno
        run: |
          echo "Este es el valor de platform: ${{ env.platform }}"
          echo "Este es el valor de region: ${{ env.region }}"
          echo "Este es el valor de account: ${{ env.account }}"