name: CI
on: [push]

env:
  platform: aws # Se cambia para probar la condicional
  # ... otras variables

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display message
        run: echo "Hola mundo"

      # Este paso solo corre si la plataforma coincide
      - name: Mostrando variables de entorno
        if: ${{ env.platform == 'aws' }} 
        run: |
          echo "Este es el valor de platform: ${{ env.platform }}"
          # ... otros echos

      - name: Mostrando evento
        run: echo "${{ toJSON(github.event) }}"

      - name: Mostrando variables por defecto
        run: |
          echo "El actor es: ${{ github.actor }}"
          echo "El repositorio es: ${{ github.repository }}"