name: CI
on: [push]

env:
  # Mapeo de secrets a variables de entorno para poder usarlos en condicionales
  username: ${{ secrets.USERNAME }} 
  password: ${{ secrets.PASSWORD }}
  platform: aws

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display message
        run: echo "Hola mundo"

      # Paso condicional basado en Secrets
      - name: Mostrando valores solo si el usuario es correcto
        if: ${{ env.username == 'Fast' && env.password != '' }}
        run: echo "Si existe usuario y contraseña"

      # Uso de variables de repositorio (no secrets)
      - name: Mostrando variable de repositorio
        run: echo "Versión del proyecto: ${{ vars.PROJECT_VERSION }}"